baseURL: "https://alarsyo.com/"
title: "Antoine's Website"

DefaultContentLanguage: en

languages:
  en:
    lang: en
    languageName: English
    weight: 1

pygmentsCodeFences: true
pygmentsStyle: dracula
