baseURL: "https://blog.alarsyo.net/"
title: "Antoine Martin"

DefaultContentLanguage: en

languages:
  en:
    lang: en
    languageName: English
    weight: 1

pygmentsCodeFences: true
pygmentsStyle: dracula

enableRobotsTXT: true
