baseURL: "https://blog.alarsyo.com/"
title: "Antoine's Website"

theme: my-simple-theme

DefaultContentLanguage: en

languages:
  en:
    lang: en
    languageName: English
    weight: 1

pygmentsCodeFences: true
pygmentsStyle: dracula
