[build]
  command = "hugo --verbose --minify --gc"
  publish = "public/"

[build.environment]
  HUGO_VERSION = "0.78.1"
  HUGO_ENV = "production"
  NODE_VERSION="11"

[context.branch-deploy]
  command = "hugo --verbose --minify --gc -b $DEPLOY_PRIME_URL"
